config/routes.rb
TypeATracking::Application.routes.draw do

  resources :machines, :assembly_projects
  root 'machines#index'
  get 'assembly_process/edit' => 'assembly_process#edit'
  post 'assembly_process/edit' => 'assembly_process#update'

  

end

app/models/assem_task.rb
class AssemTask < ActiveRecord::Base
	belongs_to :subassembly
	has_many :assem_tasks_machines
	validates :title, :presence => true
end

app/models/assem_tasks_machine.rb
class AssemTasksMachine < ActiveRecord::Base
	belongs_to :machine 
	belongs_to :assem_task
	delegate :subassembly, :to => :assem_task
	delegate :title, :to => :assem_task
	delegate :description, :to => :assem_task


end

app/models/assembly_project.rb
class AssemblyProject < ActiveRecord::Base
	belongs_to :machine
end

app/models/machine.rb
class Machine < ActiveRecord::Base
	has_one :assembly_project
	has_many :assem_tasks_machines
end

app/models/subassembly.rb
class Subassembly < ActiveRecord::Base
	has_many :assem_tasks
	validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assembly_process_controller.rb
class AssemblyProcessController < ApplicationController
	def edit
		@subassemblies = Subassembly.order("stage")
	end
end

app/controllers/assembly_projects_controller.rb
class AssemblyProjectsController < ApplicationController
	include Sorting

	def show
		@assembly_project = AssemblyProject.find(params[:id])
		@machine = @assembly_project.machine
		tasks = @machine.assem_tasks_machines
		@subassemblies = Subassembly.all
		@sorted_tasks = hash_by_subassembly(tasks)
	end

end

app/controllers/concerns/sorting.rb
module Sorting
	extend ActiveSupport::Concern

	def hash_by_subassembly(tasks)
		@subassemblies = Subassembly.all
		results = {}
		@subassemblies.each do |sa|
			results[sa] = tasks.select { |t| t.subassembly == sa }
		end
		return results
	end

end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
	def index
		@machines = Machine.all
	end

	def new
		@machine = Machine.new
	end

	def create
		p params
		@machine = Machine.new(machine_params)
		@machine.build_assembly_project
		@tasks = AssemTask.all
		@tasks.each do |t|
			@machine.assem_tasks_machines.build(:assem_task_id => t.id)
		end
		if @machine.save
			redirect_to machines_path
		else
			render :new
			puts "Issue with machine creation"
		end
	end

	private
  def machine_params
    params.require(:machine).permit(:serial_num, :customer_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/assembly_process/edit.html.erb
<h2>Update the Assembly Process</h2>

<ul class='subassemblies-list'>
	<% @subassemblies.each do |sa| %>
		<li><%= "Stage: " + sa.stage.to_s + " - " + sa.name %></li>
			<ul>
				<% sa.assem_tasks.each do |task| %>
					<li><%= task.title %></li>
				<% end %>
			</ul>
	<% end %>
</ul>

app/views/assembly_projects/show.html.erb
<h2>Track Machine Assembly</h2>
<h4>Serial Number: <%= @machine.serial_num %></h4>

<% @subassemblies.each do |sa| %>
	<div class='subassembly-block'>
		<h3><%= sa.name %></h3>
		<ol>
			<% @sorted_tasks[sa].each do |t| %>
				<li>
					<%= form_tag ("/complete_task/#{t.id}") do %>
						<% if t.complete? %>
							<%= label_tag(t.id, t.title, :class => 'complete')  %>
							<%= check_box_tag(t.id, "1", true) %>
						<% else %>
							<%= label_tag(t.id, t.title, :class => 'incomplete')  %>
							<%= check_box_tag(t.id, "1") %>
						<% end %>
					<% end %>
				</li>
			<% end %>
		</ol>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TypeATracking</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/machines/index.html.erb
<h2>All Machines</h2>

<%= link_to "Start New Machine", new_machine_path %>

<ul class='machines-list'>
	<li>
		<ul class='headers'>
			<li>Serial Number</li>
		</ul>
	</li>
	<% @machines.each do |m| %>
		<li>
			<ul class='machine-info'>
				<li><%= link_to m.serial_num, m %></li>
				<li><%= link_to "Continue Assembly", m.assembly_project %></li>
			</ul>
		</li>
	<% end %>
</ul>

app/views/machines/new.html.erb
<h2>Begin a New Machine</h2>

<%= form_for @machine do |f| %>
	<%= f.label 'Serial Number' %>
	<%= f.text_field :serial_num %>
	<%= f.label "Customer ID" %>
	<%= f.text_field :customer_id %>
	<%= f.submit %>
<% end %>